import React, { useState, useEffect } from 'react';
import { 
  Compass, 
  MapPin, 
  Clock, 
  TrendingUp, 
  ShieldAlert, 
  CheckCircle2, 
  Cpu, 
  ArrowRight, 
  Layers, 
  ShieldCheck, 
  FileText, 
  HelpCircle 
} from 'lucide-react';
import { runPrediction, fetchComplaintById } from '../services/api';

export default function PredictionPage({ activeCaseId, onSelectCase, onNavigate }) {
  const [caseId, setCaseId] = useState(activeCaseId || 'CMP-1001');
  const [predictionResult, setPredictionResult] = useState(null);
  const [loading, setLoading] = useState(false);
  const [caseMeta, setCaseMeta] = useState(null);

  useEffect(() => {
    if (activeCaseId && activeCaseId !== caseId) {
      setCaseId(activeCaseId);
    }
  }, [activeCaseId]);

  function executePrediction(targetId) {
    setLoading(true);
    fetchComplaintById(targetId)
      .then(c => setCaseMeta(c))
      .catch(console.error);

    runPrediction(targetId)
      .then(res => {
        setPredictionResult(res);
        setLoading(false);
      })
      .catch(err => {
        console.error(err);
        setLoading(false);
      });
  }

  useEffect(() => {
    executePrediction(caseId);
  }, [caseId]);

  const topCandidate = predictionResult?.top_ranked_candidate;
  const allCandidates = predictionResult?.all_ranked_candidates || [];
  const muleChain = predictionResult?.analyzed_mule_chain || {};
  const metadata = predictionResult?.model_metadata || {};

  return (
    <div className="p-6 space-y-6">
      
      {/* Header */}
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 pb-2 border-b border-navy-800">
        <div>
          <div className="flex items-center gap-2">
            <h1 className="text-xl font-bold font-display text-white tracking-wide">
              EXPLAINABLE CASH-WITHDRAWAL LOCATION PREDICTION
            </h1>
            <span className="px-2 py-0.5 rounded bg-cyan-950 border border-cyan-500/40 text-cyan-300 font-mono text-[10px] font-bold">
              MULTI-FACTOR ENSEMBLE
            </span>
          </div>
          <p className="text-xs text-slate-400 mt-1">
            Forecasting probable ATM extraction kiosks from multi-hop mule telemetry to enable proactive police interception.
          </p>
        </div>

        {/* Case Selector and Re-run Button */}
        <div className="flex items-center gap-2 self-start md:self-auto font-mono text-xs">
          <select
            value={caseId}
            onChange={(e) => {
              setCaseId(e.target.value);
              onSelectCase(e.target.value);
            }}
            className="bg-navy-950 border border-cyan-600 rounded-lg px-3 py-2 text-cyan-300 font-bold focus:outline-none focus:border-cyan-400 cursor-pointer"
          >
            <optgroup label="Walkthrough Cases (With Ground Truth)">
              <option value="CMP-1001">CMP-1001 (UPI Phishing ₹95k)</option>
              <option value="CMP-1002">CMP-1002 (Task Scam ₹142k)</option>
              <option value="CMP-1003">CMP-1003 (Stock Advisory ₹210k)</option>
              <option value="CMP-1004">CMP-1004 (Electricity Phishing ₹68k)</option>
              <option value="CMP-1005">CMP-1005 (Loan App Extortion ₹185k)</option>
              <option value="CMP-1006">CMP-1006 (SIM Swap OTP ₹74k)</option>
              <option value="CMP-1007">CMP-1007 (Crypto Arbitrage ₹320k)</option>
              <option value="CMP-1008">CMP-1008 (Card Skimming ₹115k)</option>
            </optgroup>
          </select>

          <button
            onClick={() => executePrediction(caseId)}
            className="px-3.5 py-2 bg-gradient-to-r from-cyan-600 to-blue-600 hover:from-cyan-500 text-white rounded-lg font-semibold shadow-md transition flex items-center gap-1.5"
          >
            <Compass className="w-3.5 h-3.5" />
            <span>Re-run Inference</span>
          </button>
        </div>
      </div>

      {/* Mandatory Demonstration Disclaimer Banner */}
      <div className="p-3.5 rounded-xl bg-amber-950/60 border border-amber-600/50 flex items-start gap-3 text-xs text-amber-200">
        <ShieldCheck className="w-5 h-5 text-amber-400 shrink-0 mt-0.5" />
        <div className="leading-relaxed">
          <strong className="text-amber-300 font-mono">Demonstration Result — Trained on Synthetic Dataset (TRL 3 Experimental):</strong>
          <span className="text-slate-300 ml-1">
            Probabilities generated by rule-informed multi-factor spatial logic. Does not represent definitive proof of criminal activity. Physical patrol dispatch must be confirmed by an investigating officer.
          </span>
        </div>
      </div>

      {loading ? (
        <div className="p-16 flex flex-col items-center justify-center font-mono text-cyan-400 space-y-3">
          <Cpu className="w-8 h-8 animate-spin" />
          <span>Evaluating Multi-Hop Mule Proximity & Temporal Windows...</span>
        </div>
      ) : (
        <>
          {/* Top Ranked Prediction Card (Highlight) */}
          {topCandidate && (
            <div className="glass-panel p-6 rounded-2xl border-cyan-500/60 bg-gradient-to-br from-navy-900 via-navy-950 to-navy-900 shadow-2xl relative overflow-hidden">
              <div className="absolute top-0 right-0 px-4 py-1.5 rounded-bl-xl bg-cyan-950 border-l border-b border-cyan-500/50 text-cyan-300 font-mono text-xs font-bold flex items-center gap-1.5">
                <Compass className="w-3.5 h-3.5 text-cyan-400" />
                <span>TOP RANKED FORECAST (RANK #1)</span>
              </div>

              <div className="grid grid-cols-1 lg:grid-cols-3 gap-6 pt-2">
                
                {/* Candidate Overview */}
                <div className="space-y-4">
                  <div>
                    <span className="text-xs text-cyan-400 font-mono font-semibold">
                      ATM KIOSK / CASH EXTRACTION POINT
                    </span>
                    <h2 className="text-xl font-bold font-display text-white mt-1">
                      {topCandidate.name}
                    </h2>
                    <p className="text-xs text-slate-400 font-mono flex items-center gap-1.5 mt-1">
                      <MapPin className="w-3.5 h-3.5 text-purple-400" />
                      <span>{topCandidate.jurisdiction} • {topCandidate.type}</span>
                    </p>
                  </div>

                  {/* Confidence Metric Circle */}
                  <div className="flex items-center gap-4 p-4 rounded-xl bg-navy-950/80 border border-navy-800">
                    <div className="w-16 h-16 rounded-full border-4 border-cyan-400/80 bg-cyan-950/60 flex flex-col items-center justify-center font-display font-bold text-white shadow-inner">
                      <span className="text-xl leading-none">{topCandidate.confidence_percentage}%</span>
                      <span className="text-[9px] font-mono text-cyan-300">CONF</span>
                    </div>

                    <div className="font-mono text-xs space-y-1">
                      <div>
                        <span className="text-slate-400">Estimated Distance: </span>
                        <span className="text-emerald-400 font-bold">~{topCandidate.distance_km} km</span>
                      </div>
                      <div>
                        <span className="text-slate-400">Past Cashout Hits: </span>
                        <span className="text-purple-400 font-bold">{topCandidate.historical_cashouts} incidents</span>
                      </div>
                      <div>
                        <span className="text-slate-400">Target FIR Value: </span>
                        <span className="text-amber-400 font-bold">₹{caseMeta?.amount?.toLocaleString() || '95,000'}</span>
                      </div>
                    </div>
                  </div>

                  {/* Traced Chain */}
                  <div className="p-3 rounded-lg bg-navy-950/60 border border-navy-800/80 font-mono text-[11px] text-slate-300 space-y-1">
                    <span className="text-[10px] text-slate-500 uppercase block">Traced Mule Pipeline</span>
                    <div className="flex items-center gap-1.5 text-xs">
                      <span className="text-slate-400">{muleChain.entry_mule_l1 || 'ACC-MULE-001'}</span>
                      <ArrowRight className="w-3 h-3 text-cyan-400" />
                      <span className="text-rose-400 font-bold">{muleChain.layering_mule_l2 || 'ACC-MULE-004'}</span>
                      <ArrowRight className="w-3 h-3 text-cyan-400" />
                      <span className="text-purple-300 font-semibold">{topCandidate.location_id}</span>
                    </div>
                  </div>
                </div>

                {/* Plain-Language Explainability Breakdown (Core Requirement) */}
                <div className="lg:col-span-2 space-y-4">
                  <div className="flex items-center justify-between border-b border-navy-800 pb-2">
                    <h3 className="text-sm font-semibold text-white font-mono flex items-center gap-2">
                      <HelpCircle className="w-4 h-4 text-cyan-400" />
                      PLAIN-LANGUAGE EXPLAINABILITY FACTORS
                    </h3>
                    <span className="text-[10px] text-slate-400 font-mono">
                      Transparent Feature Attribution
                    </span>
                  </div>

                  {/* Plain Language Bullets */}
                  <div className="space-y-2.5">
                    {topCandidate.plain_language_reasons?.map((reason, idx) => (
                      <div 
                        key={idx}
                        className="p-3 rounded-xl bg-navy-950/70 border border-navy-800 flex items-start gap-3"
                      >
                        <span className="w-6 h-6 rounded-lg bg-cyan-500/20 text-cyan-300 font-mono text-xs flex items-center justify-center font-bold shrink-0 mt-0.5">
                          #{idx + 1}
                        </span>
                        <p className="text-xs text-slate-200 leading-relaxed font-sans">
                          {reason}
                        </p>
                      </div>
                    ))}
                  </div>

                  {/* Feature Attribution Weights Bar */}
                  {topCandidate.contributing_features && (
                    <div className="pt-2">
                      <h4 className="text-[10px] font-mono uppercase text-slate-400 mb-2">
                        COMPUTED FACTOR CONTRIBUTION WEIGHTS
                      </h4>
                      <div className="grid grid-cols-2 sm:grid-cols-4 gap-2 font-mono text-[10px]">
                        <div className="p-2 rounded bg-navy-950 border border-navy-800">
                          <span className="text-slate-400 block">Mule Chain Affinity</span>
                          <span className="text-rose-400 font-bold text-xs">{topCandidate.contributing_features.mule_chain_affinity}%</span>
                        </div>
                        <div className="p-2 rounded bg-navy-950 border border-navy-800">
                          <span className="text-slate-400 block">Branch Proximity</span>
                          <span className="text-emerald-400 font-bold text-xs">{topCandidate.contributing_features.geospatial_proximity}%</span>
                        </div>
                        <div className="p-2 rounded bg-navy-950 border border-navy-800">
                          <span className="text-slate-400 block">Temporal Match</span>
                          <span className="text-amber-400 font-bold text-xs">{topCandidate.contributing_features.temporal_window_match}%</span>
                        </div>
                        <div className="p-2 rounded bg-navy-950 border border-navy-800">
                          <span className="text-slate-400 block">Hub Density</span>
                          <span className="text-purple-400 font-bold text-xs">{topCandidate.contributing_features.historical_density}%</span>
                        </div>
                      </div>
                    </div>
                  )}

                  {/* Operational Action Buttons */}
                  <div className="flex flex-wrap items-center gap-3 pt-2">
                    <button
                      onClick={() => onNavigate('intelligence')}
                      className="px-4 py-2 bg-gradient-to-r from-purple-600 to-indigo-600 hover:from-purple-500 text-white rounded-lg font-mono text-xs font-semibold shadow-lg transition flex items-center gap-1.5"
                    >
                      <ShieldAlert className="w-3.5 h-3.5" />
                      <span>Issue Police Dispatch Dossier</span>
                    </button>
                    <button
                      onClick={() => onNavigate('map')}
                      className="px-4 py-2 bg-navy-800 hover:bg-navy-700 text-cyan-300 border border-navy-700 rounded-lg font-mono text-xs transition flex items-center gap-1.5"
                    >
                      <MapPin className="w-3.5 h-3.5 text-cyan-400" />
                      <span>Plot on Geospatial Grid</span>
                    </button>
                  </div>
                </div>

              </div>
            </div>
          )}

          {/* Secondary Ranked Candidates Table */}
          <div className="glass-panel p-5 rounded-xl border-navy-800 space-y-4">
            <div className="flex items-center justify-between">
              <div>
                <h3 className="text-sm font-semibold text-white font-mono flex items-center gap-2">
                  <Layers className="w-4 h-4 text-cyan-400" />
                  RANKED CANDIDATE LOCATIONS (TOP 5 ENSEMBLE)
                </h3>
                <p className="text-xs text-slate-400">
                  Alternative ATM locations within transit radius evaluated by the probabilistic spatial engine.
                </p>
              </div>
            </div>

            <div className="overflow-x-auto rounded-lg border border-navy-800 font-mono text-xs">
              <table className="w-full text-left">
                <thead className="bg-navy-950 text-[10px] uppercase text-slate-400">
                  <tr>
                    <th className="py-2.5 px-4">Rank</th>
                    <th className="py-2.5 px-4">ATM / Kiosk Name</th>
                    <th className="py-2.5 px-4">Jurisdiction</th>
                    <th className="py-2.5 px-4">Confidence %</th>
                    <th className="py-2.5 px-4">Distance</th>
                    <th className="py-2.5 px-4">Primary Rationale</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-navy-800/60">
                  {allCandidates.slice(0, 5).map((cand, idx) => (
                    <tr 
                      key={cand.location_id}
                      className={idx === 0 ? 'bg-cyan-950/20 font-semibold' : 'hover:bg-navy-850/50'}
                    >
                      <td className="py-3 px-4">
                        <span className={`px-2 py-0.5 rounded text-[10px] font-bold ${
                          idx === 0 
                            ? 'bg-cyan-500 text-black' 
                            : 'bg-navy-800 text-slate-400'
                        }`}>
                          #{idx + 1}
                        </span>
                      </td>
                      <td className="py-3 px-4 text-slate-200">
                        {cand.name}
                      </td>
                      <td className="py-3 px-4 text-slate-400 text-[11px]">
                        {cand.jurisdiction}
                      </td>
                      <td className="py-3 px-4 font-bold text-cyan-300">
                        {cand.confidence_percentage}%
                      </td>
                      <td className="py-3 px-4 text-slate-300">
                        ~{cand.distance_km} km
                      </td>
                      <td className="py-3 px-4 text-slate-300 text-[11px] max-w-[280px] truncate">
                        {cand.plain_language_reasons?.[0] || 'Statistical regional candidate.'}
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </div>
        </>
      )}

    </div>
  );
}
